# Model arguments
model_name_or_path: "Minsukim/internlm_1_8_sft_bf16" #Minsukim/internlm_1_8_sft_bf16 #openai-community/gpt2 deepseek-ai/DeepSeek-Prover-V1.5-SFT
model_revision: main
torch_dtype: bf16
attn_implementation: flash_attention_2
trust_remote_code: true
# Data training arguments
dataset_name: workbook
dataset_split: train
preprocessing_num_workers: 24

# SFT trainer config
bf16: true
do_eval: false
tf32: true
torch_compile: true
optim: paged_adamw_8bit   #adamw_torch_fused
gradient_accumulation_steps: 8
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: true
hub_model_id: Minsukim/deepseek_GRPO_baseline_workbookdata
output_dir: /projects/minsu/ATP_checkpoints/deepseek_GRPO_baseline_workbookdata
log_level: info
logging_steps: 10
logging_strategy: steps

save_strategy: "steps"
save_steps: 100
save_total_limit: 1
hub_strategy: "end"



resume_from_checkpoint: true


beta: 0.04
learning_rate: 1.0e-05
temperature: 0.9


lr_scheduler_type: cosine
max_steps: -1
num_train_epochs: 1
overwrite_output_dir: true
per_device_train_batch_size: 8
remove_unused_columns: true
report_to:
- tensorboard
- wandb
seed: 42
warmup_ratio: 0.1
num_generations: 4
num_iterations: 2
use_vllm: true
vllm_gpu_memory_utilization: 0.5
max_completion_length: 2048   #gpt2: 256, others: 2048
max_prompt_length: 512
use_peft: true
load_in_4bit: false
load_in_8bit: false
lora_r: 16
lora_alpha: 16



# Hub
push_to_hub: true
hub_private_repo: true
wandb_project: ATP
wandb_entity: kimminsu
