# Model arguments
model_name_or_path: internlm/internlm2-math-plus-1_8b
model_revision: main
torch_dtype: bf16
attn_implementation: flash_attention_2

# Data training arguments
dataset_name: deepseek
dataset_split: train
preprocessing_num_workers: 48

# SFT trainer config
bf16: true
do_eval: false
tf32: true
torch_compile: true
optim: paged_adamw_8bit
gradient_accumulation_steps: 4
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
hub_model_id: Minsukim/internlm_1_8_sft_deepseek
output_dir: /projects/minsu/ATP_checkpoints/internlm_1_8_sft_deepseek
learning_rate: 1.0e-05
log_level: info
logging_steps: 5
logging_strategy: steps
lr_scheduler_type: cosine
max_length: 4096
max_steps: -1
num_train_epochs: 3
overwrite_output_dir: true
per_device_train_batch_size: 16
remove_unused_columns: true
trust_remote_code: true
report_to:
- tensorboard
- wandb
save_strategy: "epoch"
seed: 42
warmup_ratio: 0.1


# Hub
push_to_hub: true
hub_private_repo: true