# Model arguments
model_name_or_path: "openai-community/gpt2"   #deepseek-ai/DeepSeek-Prover-V1.5-SFT, openai-community/gpt2
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_name: minif2f
dataset_split: train
preprocessing_num_workers: 24

# SFT trainer config
bf16: true
do_eval: false
tf32: true
torch_compile: true
optim: paged_adamw_8bit
gradient_accumulation_steps: 16
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: true
hub_model_id:
output_dir: /projects/minsu/ATP_checkpoints/full_prover_test
learning_rate: 1.0e-05
log_level: info
logging_steps: 5
logging_strategy: steps
lr_scheduler_type: cosine
max_steps: -1
num_train_epochs: 1
overwrite_output_dir: true
per_device_train_batch_size: 8
remove_unused_columns: true
report_to:
- tensorboard
- wandb
save_strategy: "epoch"
seed: 42
warmup_ratio: 0.1
use_peft: false
load_in_4bit: false
load_in_8bit: false
lora_r: 16
lora_alpha: 1

# GRPO default setting
reward_type: 'lean'
beta: 0.04
num_generations: 8
num_iterations: 4
use_vllm: true
vllm_gpu_memory_utilization: 0.5
loss_function: "rloo"
token_level_kl: true
normalize_advantage: true
kl_coef: true
cliprange: 0.2
whiten_rewards: true
max_completion_length: 256   #gpt2: 256, others: 2048

# Hub
push_to_hub: true
hub_private_repo: true
wandb_project: ATP
wandb_entity: kimminsu
