# Model arguments
model_name_or_path: kfdong/STP_model_Lean_0320 #"Minsukim/DeepSeek-Prover-V1.5-7B_sft_stp_500k" #"deepseek-ai/DeepSeek-Prover-V2-7B"  # kfdong/STP_model_Lean_0320 Goedel-LM/Goedel-Prover-SFT Minsukim/internlm_1_8_sft_bf16_epoch1  #Minsukim/internlm_1_8_sft_bf16 deepseek-ai/DeepSeek-Prover-V2-7B, openai-community/gpt2
model_revision: main
torch_dtype: bf16
attn_implementation: flash_attention_2
trust_remote_code: true
# Data training arguments
dataset_name: stp
dataset_split: train
preprocessing_num_workers: 24

# SFT trainer config
bf16: true
do_eval: false
tf32: true
torch_compile: true
optim: paged_adamw_8bit   #adamw_torch_fused
gradient_accumulation_steps: 8
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: true
hub_model_id: Minsukim/stp_grpo_custom_entropy_mean_first_distribute_start_zerobaseline_1_-0.1_-1_stp_data_1024
output_dir: /projects/minsu/ATP_checkpoints/stp_grpo_custom_entropy_mean_first_distribute_start_zerobaseline_1_-0.1_-1_stp_data_1024

log_level: info
logging_steps: 10
logging_strategy: steps
lr_scheduler_type: cosine
max_steps: -1
num_train_epochs: 1
overwrite_output_dir: true
per_device_train_batch_size: 8
remove_unused_columns: true
report_to:
- tensorboard
- wandb


#resume_from_checkpoint: true

save_strategy: "steps"
save_steps: 100
save_only_model: true
#save_total_limit: 5
hub_strategy: "end"


seed: 42
warmup_ratio: 0.1
use_peft: true
load_in_4bit: false
load_in_8bit: false
lora_r: 64
lora_alpha: 64
lora_target_modules: all-linear




beta: 0.04
learning_rate: 1.0e-05 #1.0e-05 4.0e-07
temperature: 0.9



# GRPO default setting
reward_type: 'lean'

num_generations: 4
num_iterations: 2
use_vllm: true
vllm_gpu_memory_utilization: 0.5 #deepseekv2 0.65, others 0.5
max_completion_length: 1024   #gpt2: 256, others: 2048
max_prompt_length: 512
loss_function: "grpo"
token_level_kl: true
normalize_advantage: true #for rloo
kl_coef: true
cliprange: 0.2
whiten_rewards: false


alpha_advantage: 1
delta0: 1
delta1: -0.1
delta2: -1
adv_baseline: "zero"
score_assign: "all"  #last ,all,mix,start
adv_method: "label"    #return or label
parse_method: "tree"
weighted_adv: false   #true or false
first_error: true  #true or false


potent_func: false
potent_type: "exponential_step" #"exponential_step" #"distance_to_goal" #"monotone_growth" "normalized_exponential" "proof_step"
potent_positive: true
shift_potential: true   #exponential "proof_step" should be true "proof_step"
potent_coef: 0.5

#delta_clip: none

negative_dropout : false
dropout_rate: 0.5


entropy_adv: false
entropy_reg: false
entropy_coef: 0.1
entropy_position: "all"


asymmetric: false
tactic_distribution: true


positive_entropy_drop: true
divide_weight_method: mean
first_tactic_token: true
advantage_distribute_top_k: false




# Hub
push_to_hub: true
hub_private_repo: true
wandb_project: ATP
wandb_entity: kimminsu
